<section class="page-title dark-background bg-gradient-brand" style="padding:150px 0 70px;">
    <div class="container text-center" data-aos="fade-up">
        <span class="badge-brand-pink">Legal</span>
        <h1 class="mt-3 text-white">Privacy Policy</h1>
        <p style="color:rgba(255,255,255,.85); max-width:700px; margin:0 auto;">How Navuli collects, uses and protects school, staff, student and parent information.</p>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 mx-auto" data-aos="fade-up">
                <p class="text-muted small mb-5">Last updated: 11 September 2026</p>

                <h3>1. Introduction</h3>
                <p>This Privacy Policy explains how Navuli Fiji ("Navuli", "we", "us", "our") collects, uses, discloses and protects information through the Navuli school management platform ("Service"). It applies to School Administrators, teachers and other staff, students, and parents/guardians who use the Service.</p>
                <p>Schools that subscribe to Navuli act as the data controller for the student and staff records they enter into the Service; Navuli acts as a data processor, handling that data on the school's behalf and in line with this Policy.</p>

                <h3>2. Information We Collect</h3>
                <p>Depending on your role, the Service may hold:</p>
                <ul>
                    <li><strong>Account &amp; profile data:</strong> name, email, phone number, photo, role, and login credentials.</li>
                    <li><strong>Academic records:</strong> enrolment, timetable, attendance, assignments, assessments and report cards.</li>
                    <li><strong>Conduct and medical information:</strong> disciplinary incidents and appeals, and health/medical notes entered by authorised school staff, where the school chooses to record these in the Service.</li>
                    <li><strong>Lesson content and documents:</strong> files, lesson materials, videos and other documents uploaded by staff or students, together with any files shared through the Service's document manager, including public share links created by a user.</li>
                    <li><strong>Communications:</strong> messages, classroom discussion posts, wall posts and related media exchanged within the Service.</li>
                    <li><strong>Billing information:</strong> for schools on a paid plan, subscription and payment details necessary to process fees.</li>
                    <li><strong>Technical and usage data:</strong> IP address, device/browser information, and log data generated by using the Service, used for security and troubleshooting.</li>
                </ul>

                <h3>3. How We Use Information</h3>
                <p>We use the information collected to operate and improve the Service, including to: provide the features a user's role and subscription plan entitle them to; enable communication between staff, students and parents/guardians; generate attendance and academic records and reports; process subscription payments; secure accounts and investigate misuse; and respond to support requests.</p>

                <h3>4. Children's Data and Parental Access</h3>
                <p>Navuli is used by schools to manage records belonging to students, including minors. Student accounts are created and managed by the subscribing school, and parent/guardian accounts are linked to their child's record by the school so that parents can view relevant information (such as attendance, assessments and communications) about their own child. Schools are responsible for obtaining any consent required from parents/guardians under their own enrolment policies before entering a student's information into the Service.</p>

                <h3>5. Legal Basis for Processing</h3>
                <p>We process School Data on the instructions of the subscribing school, which is responsible for ensuring it has a lawful basis (such as its enrolment agreement with parents/guardians or legitimate educational interest) for the records it enters into the Service.</p>

                <h3>6. How We Share Information</h3>
                <p>We do not sell School Data. Within the Service, information is shared only with users whose role and permissions entitle them to see it (for example, a class teacher, a student's parent/guardian, or school administration). We may share information with:</p>
                <ul>
                    <li><strong>Service providers</strong> who support hosting, email/SMS delivery, or payment processing on our behalf, under obligations to protect the data;</li>
                    <li><strong>Legal authorities</strong> where required by law, court order, or to protect the safety of a student or member of the public.</li>
                </ul>

                <h3>7. Data Security</h3>
                <p>The Service uses role-based access control so that staff, students and parents/guardians only see information relevant to their role, together with authentication safeguards such as two-factor login for staff accounts. Files shared through the document manager's public link feature are only accessible to holders of the unique, unguessable link, which can be revoked at any time by the person who created it. While we take reasonable technical and organisational measures to protect information, no system can guarantee absolute security.</p>

                <h3>8. Data Retention</h3>
                <p>We retain School Data for as long as a school's subscription is active and as needed to comply with the school's own record-keeping obligations. Following termination of a subscription, School Data may be retained for a limited period to allow export, after which it is deleted or anonymised in accordance with our standard retention practices, except where longer retention is required by law.</p>

                <h3>9. Your Rights</h3>
                <p>Depending on your role, you may request access to, correction of, or deletion of personal information held about you or, for a parent/guardian, your child, by contacting your School Administrator or Navuli directly using the details below. Requests relating to School Data are generally directed through the subscribing school, as the data controller.</p>

                <h3>10. Cookies and Similar Technologies</h3>
                <p>The Service uses strictly necessary cookies to keep you signed in and to remember basic preferences (such as light/dark theme). We do not use these cookies for third-party advertising.</p>

                <h3>11. International Data Handling</h3>
                <p>School Data is hosted on infrastructure used to provide the Service to schools in Fiji. Where any processing occurs outside Fiji (for example, through a hosting or communications provider), we take steps to ensure it is handled consistently with this Policy.</p>

                <h3>12. Changes to This Privacy Policy</h3>
                <p>We may update this Privacy Policy from time to time to reflect changes in our practices or for legal or operational reasons. We will post the updated policy on this page and revise the "Last updated" date above.</p>

                <h3>13. Contact Us</h3>
                <p>Questions about this Privacy Policy, or requests relating to your data, can be directed to:</p>
                <ul>
                    <li><strong>Email:</strong> <a href="mailto:info@navulifiji.com">info@navulifiji.com</a></li>
                    <li><strong>Phone:</strong> <a href="tel:+6799896700">+679 989 6700</a></li>
                    <li><strong>Address:</strong> 6 Miles, Tacirua, Suva, Fiji Islands</li>
                </ul>
                <p><a href="<?= site_url('terms') ?>">Read our Terms of Use →</a></p>
            </div>
        </div>
    </div>
</section>
